### ISSUE TITLE
The compilation fails

### ISSUE THREAD

**Issue by dmace7** [sagarchalise/geany-emmet#1]
When I launch  : `gcc -c geany-emmet.cpp -fPIC `pkg-config --cflags geany``
I get the following error : `geany-emmet.cpp:37:19: fatal error: jsapi.h: No such file or directory
`

**Comment by sagarchalise** [comment]
Did you try `make` from provided makefile ? What platform/os were you trying it in ?

**Comment by sagarchalise** [comment]
Closing this as no further info ?
